[project]
name = "secrets-provisioner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.20",
]

[tool.uv]
package=true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
secrets-provisioner = "secrets_provisioner.main:main"
